
name: AWS OIDC GITHUB Demo
on:
  push:
    branches: [ "main" ]
env:
  AWS_REGION : "us-east-1"   
permissions:
      id-token: write
      contents: read

jobs:
  OIDC:
    name: 'OIDC'
    runs-on: ubuntu-latest
    environment: oidc
    defaults:
      run:
        shell: bash
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::992382544923:role/githuboidcrole
          ## role-session-name: ghrole2
          aws-region: ${{ env.AWS_REGION }}
     ## - name: Print Assumed Role
     ##  run: aws sts get-caller-identity   
      - name: Print s3 buckets
        run: aws s3 ls
