name: AWS oidc
on:
  push:
    branches: [ "main" ]
env:
  AWS_REGION : "us-east-1"   
permissions:
      id-token: write
      contents: read

jobs:
  OIDC:
    name: 'OIDC'
    runs-on: ubuntu-latest
    environment: oidc
    defaults:
      run:
        shell: bash
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} 
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
         terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
